services:
  lmsbackend:
    image: lmsbackend
    build:
      context: lms-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
    command: ["sh", "-c", "npx prisma migrate deploy && if [ \"$SEED_ON_STARTUP\" = \"true\" ]; then node prisma/seed.js; fi && node --inspect=0.0.0.0:9229 server.js"]
