services:
  lmsbackend:
    image: lmsbackend
    build:
      context: lms-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
