services:
  lmsbackend:
    image: lmsbackend
    build:
      context: lms-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000

  lmsfrontend:
    image: lmsfrontend
    build:
      context: lms-frontend
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: http://lmsbackend:3000/api
    ports:
      - 5173:80
    depends_on:
      - lmsbackend
